from influx_line_protocol import Metric
f1 =open('/home/syedasamreen/Downloads/ipmidata.txt','r')
line = f1.readline()
l = line.replace('|','')
l1= l.strip().split()
# print(l1)
now = datetime.now()
current_time = now.strftime("%H:%M:%S")
metric = Metric("CPU_metric")
metric.with_timestamp(1570977942581909918)
metric.add_tag("CPU_name",l1[0])
metric.add_tag("SENS",l1[1])
metric.add_value("value",l1[2])
metric.add_value("unit",l1[3])
metric.add_value("status",l1[5])
print(metric)
